### ISSUE TITLE
Floating Top Hat

### ISSUE THREAD

**Issue by medsal15** [cyanobacterium/DrCyanosWonderfulWands#5]
![2015-03-09_17 48 02](https://cloud.githubusercontent.com/assets/8267354/6559679/c122ba58-c684-11e4-9518-c7cac344309b.png)

**Comment by cyanobacterium** [comment]
The head coordinates (as seen by the hat renderer class) don't change when you sneak, requiring special handling when sneaking. I'm aware of this bug, but it has a very low priority.

**Comment by cyanobacterium** [comment]
Was fixed in the 1.9 version, I think.
