### ISSUE TITLE
wisp wand crashed Dedicated server during play

### ISSUE THREAD

**Issue by kreezxil** [cyanobacterium/DrCyanosWonderfulWands#6]
Issue: wisp wand crashed Dedicated server during play

crash report:
https://gist.github.com/45259ada13dc4cbfdd3e

fml server latest:
https://gist.github.com/0a7a127227e387ca6b7f

**Comment by cyanobacterium** [comment]
I'll look into it and see if I can fix it.

**Comment by cyanobacterium** [comment]
I implemented a fix in version 1.7.1

**Comment by kreezxil** [comment]
cool thanks.
